name: MTSMP
version: '${project.version}'
main: de.nikogenia.mtsmp.Main
api-version: '1.20'
authors: [Nikogenia]
description: The Paper plugin for a SMP server of the server network management engine MineTower
depend:
  - MTBase
commands:
  shop:
    description: "Shop information and administration"
    usage: "Type '/shop help' for more information!"
